"
A topic map is a standard for the representation and interchange of knowledge, with an emphasis on the findability of information. Topic maps were originally developed in the late 1990s as a way to represent back-of-the-book index structures so that multiple indexes from different sources could be merged. [wikipedia](https://en.wikipedia.org/wiki/Topic_map)
"
Class {
	#name : 'FwTopicMap',
	#superclass : 'Object',
	#category : 'Federated-Wiki-dmx',
	#package : 'Federated-Wiki',
	#tag : 'dmx'
}
